DROP TABLE IF EXISTS  users;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  authority VARCHAR(50) NOT NULL,
  enabled INT NOT NULL DEFAULT 1,
  email VARCHAR(50) NOT NULL
);
